# Generated by Django 5.0.14 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
    ]
