# Generated by Django 5.0.14 on 2026-08-04 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=150)),
                ('lecturer_name', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to='handouts/')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_copy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='print_jobs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='handout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.handout'),
        ),
    ]
