# Generated by Django 5.0.14 on 2026-08-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_handout_alter_order_file_order_handout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='handout',
            name='price_per_copy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
