# Generated by Django 5.0.14 on 2026-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_handout_is_active_alter_handout_price_per_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
