# Generated by Django 5.0.14 on 2026-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
