# Generated by Django 5.0.14 on 2026-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_print_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handout',
            name='semester',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handout',
            name='page_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
