# Generated by Django 5.0.14 on 2026-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_handout_contact_number_handout_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='file',
            field=models.FileField(help_text='PDF only, max 50MB.', upload_to='handouts/'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
