# Generated by Django 5.0.14 on 2026-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_handout_file_alter_handout_page_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw_rate_per_page', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('color_rate_per_page', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
            ],
        ),
    ]
