# Generated by Django 5.0.14 on 2026-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pricingsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingsettings',
            options={'verbose_name': 'Pricing Settings', 'verbose_name_plural': 'Pricing Settings'},
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='handout_rate_per_page',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
        ),
    ]
